-- 机构基本信息
TRUNCATE TABLE MBT_OS_BORROWERS;

INSERT INTO MBT_OS_BORROWERS
 SELECT *
   FROM CCT_T_CONVERT_BORROWERS T
  WHERE  T.OPERATION_TYPE != '4'
    AND T.BAT_DATE = '20170512';
  COMMIT;

TRUNCATE TABLE MBT_OS_REGCAPITALS;

INSERT INTO MBT_OS_REGCAPITALS
 SELECT *
   FROM CCT_T_CONVERT_REGCAPITALS T
  WHERE  T.OPERATION_TYPE != '4'
    AND T.BAT_DATE = '20170512';
  COMMIT;

 TRUNCATE TABLE MBT_OS_FINANCECONTACTS;

 INSERT INTO MBT_OS_REGCAPITALS
  SELECT *
    FROM CCT_T_CONVERT_REGCAPITALS T
   WHERE  T.OPERATION_TYPE != '4'
     AND T.BAT_DATE = '20170512';
   COMMIT;

 TRUNCATE TABLE MBT_OS_SUPERMANS;

 INSERT INTO MBT_OS_SUPERMANS
  SELECT *
    FROM CCT_T_CONVERT_SUPERMANS T
   WHERE  T.OPERATION_TYPE != '4'
     AND T.BAT_DATE = '20170512';
   COMMIT;

 TRUNCATE TABLE MBT_OS_GRPCORPS;

 INSERT INTO MBT_OS_GRPCORPS
  SELECT *
    FROM CCT_T_CONVERT_GRPCORPS T
   WHERE  T.OPERATION_TYPE != '4'
     AND T.BAT_DATE = '20170512';
   COMMIT;
