UPDATE CCI_CONTRACT_INFO
   SET CUSTOMER_CODE =
       (SELECT MAX(CUSTOMER_CODE)
          FROM CCI_ORGINFO_BASIC
         WHERE CCI_CONTRACT_INFO.LOAN_CARD_NO =
               CCI_ORGINFO_BASIC.LOAN_CARD_NO);
