UPDATE CCI_CONTRACT_INFO
   SET CUSTOMER_CODE = T.CUSTOMER_CODE
  FROM (SELECT MAX(CUSTOMER_CODE), LOAN_CARD_NO
  		FROM CCI_ORGINFO_BASIC
 		GROUP BY LOAN_CARD_NO) T
  WHERE EXISTS (
		SELECT 1 FROM T
		WHERE T.LOAN_CARD_NO = CCI_CONTRACT_INFO.LOAN_CARD_NO);
